fix(backends/lean): `as` is a keyword
AeneasVerif/aeneas pull request #146
Opened 2024-04-17 12:30 UTC by RaitoBezarius

`as` is a reserved keyword and cannot be used as a variable name.

Fixes #139.

cc @sonmarcho

2024-04-17 15:02 UTC, sonmarcho commented
Can you also add "from" as a keyword?

2024-04-17 15:24 UTC, sonmarcho commented
> If we're in the process of fixing Lean keyword issues, should we complete the list using, e.g., https://github.com/leanprover/lean4/blob/master/doc/latex/lstlean.tex#L12 ?

Yes, that's a good idea. I was not aware of this list.

2024-04-17 15:24 UTC, RaitoBezarius commented
I'm doing it.

2024-04-17 15:35 UTC, RaitoBezarius commented
Done @sonmarcho @R1kM PTAL.

2024-04-18 09:28 UTC, sonmarcho requested changes
There are several keywords which are tactics, or which require to be prefixed with `#` (I think), so it should be ok to remove them.

2024-04-18 09:28 UTC, sonmarcho commented on compiler/ExtractBase.ml
> +          "check";
I think we can remove this one

2024-04-18 09:28 UTC, sonmarcho commented on compiler/ExtractBase.ml
> +          "clear";
This is a tactic? I think we can remove it

2024-04-18 09:28 UTC, sonmarcho commented on compiler/ExtractBase.ml
> +          "apply";
remove allGoals and apply: those are tactics

2024-04-18 09:28 UTC, sonmarcho commented on compiler/ExtractBase.ml
> +          "assume";
remove

2024-04-18 09:28 UTC, sonmarcho commented on compiler/ExtractBase.ml
> +          "contradiction";
remove

2024-04-18 09:28 UTC, sonmarcho commented on compiler/ExtractBase.ml
> +          "dif";
remove

2024-04-18 09:28 UTC, sonmarcho commented on compiler/ExtractBase.ml
> +          "exact";
remove those two

2024-04-18 09:28 UTC, sonmarcho commented on compiler/ExtractBase.ml
> +          "generalize";
remove

2024-04-18 09:28 UTC, sonmarcho commented on compiler/ExtractBase.ml
> +          "help";
remove

2024-04-18 09:28 UTC, sonmarcho commented on compiler/ExtractBase.ml
> +          "refine";
remove

2024-04-18 09:28 UTC, sonmarcho commented on compiler/ExtractBase.ml
> +          "this";
remove

2024-04-18 09:30 UTC, sonmarcho commented on compiler/ExtractBase.ml
> +          "return";
Remove this one: I'm actually using it

2024-04-18 11:42 UTC, RaitoBezarius commented
> There are several keywords which are tactics, or which require to be prefixed with `#` (I think), so it should be ok to remove them.

I removed all the tactics I could find, PTAL.

2024-04-18 13:48 UTC, sonmarcho commented
I think we can also remove `check` and `help` because they are commands (which must be prefixed by `#`)?

2024-04-18 14:05 UTC, RaitoBezarius commented
> I think we can also remove `check` and `help` because they are commands (which must be prefixed by `#`)?

Apologies, I must have missed it, this is done now.

2024-04-19 06:22 UTC, sonmarcho approved these changes

2024-04-19 06:22 UTC, merged